# =====================================================
# AGENTSALUD MVP - DOCKER COMPOSE FOR COOLIFY + SUPABASE
# =====================================================
# Hybrid configuration: Coolify hosting + External Supabase
#
# @author AgentSalud DevOps Team
# @date January 2025

version: '3.8'

services:
  # =====================================================
  # MAIN APPLICATION
  # =====================================================
  agentsalud-app:
    build:
      context: .
      dockerfile: Dockerfile.runtime-env
    container_name: agentsalud-mvp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ENCRYPTION_IV=${ENCRYPTION_IV}
      # Supabase Configuration (External)
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
      # Evolution API Configuration
      - EVOLUTION_API_BASE_URL=${EVOLUTION_API_BASE_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - WEBHOOK_GLOBAL_URL=${WEBHOOK_GLOBAL_URL}
      # Redis Configuration
      - REDIS_URL=${REDIS_URL}
      # Feature Flags
      - FEATURE_WHATSAPP_ENABLED=${FEATURE_WHATSAPP_ENABLED}
      - FEATURE_AI_BOOKING_ENABLED=${FEATURE_AI_BOOKING_ENABLED}
      - FEATURE_ANALYTICS_ENABLED=${FEATURE_ANALYTICS_ENABLED}
      # Security & Compliance
      - HIPAA_AUDIT_ENABLED=${HIPAA_AUDIT_ENABLED}
      - SECURITY_HEADERS_ENABLED=${SECURITY_HEADERS_ENABLED}
      - CORS_ORIGIN=${CORS_ORIGIN}
      # Monitoring
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
    depends_on:
      - redis
    networks:
      - agentsalud-network
    volumes:
      - app-uploads:/app/uploads
    labels:
      - "coolify.managed=true"
      - "coolify.name=agentsalud-mvp"
      - "coolify.domain=agentsalud.com"
      - "coolify.port=3000"

  # =====================================================
  # NOTE: PostgreSQL removed - Using external Supabase
  # =====================================================
  # Database services are provided by Supabase (external)
  # This reduces complexity and maintains Supabase features

  # =====================================================
  # REDIS CACHE
  # =====================================================
  redis:
    image: redis:7-alpine
    container_name: agentsalud-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - agentsalud-network
    ports:
      - "6379:6379"
    labels:
      - "coolify.managed=true"

  # =====================================================
  # NGINX REVERSE PROXY
  # =====================================================
  nginx:
    image: nginx:alpine
    container_name: agentsalud-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - nginx-cache:/var/cache/nginx
    depends_on:
      - agentsalud-app
    networks:
      - agentsalud-network
    labels:
      - "coolify.managed=true"

  # =====================================================
  # EVOLUTION API (WHATSAPP)
  # =====================================================
  evolution-api:
    image: atendai/evolution-api:v2.0.0
    container_name: agentsalud-evolution
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - CORS_ORIGIN=https://agendia.torrecentral.com
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR
      - LOG_COLOR=true
      - DEL_INSTANCE=false
      # Using Supabase for Evolution API data storage
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=${NEXT_PUBLIC_SUPABASE_URL}/rest/v1
      - DATABASE_CONNECTION_CLIENT_NAME=supabase
      # Redis for Evolution API cache
      - REDIS_ENABLED=true
      - REDIS_URI=${REDIS_URL}
      # Webhook configuration
      - WEBHOOK_GLOBAL_URL=${WEBHOOK_GLOBAL_URL}
      - WEBHOOK_GLOBAL_ENABLED=true
      - CONFIG_SESSION_PHONE_CLIENT=AgentSalud
      - CONFIG_SESSION_PHONE_NAME=AgentSalud MVP
    volumes:
      - evolution-instances:/evolution/instances
      - evolution-store:/evolution/store
    depends_on:
      - redis
    networks:
      - agentsalud-network
    labels:
      - "coolify.managed=true"
      - "coolify.domain=evolution.agentsalud.com"
      - "coolify.port=8080"

# =====================================================
# NETWORKS
# =====================================================
networks:
  agentsalud-network:
    driver: bridge
    labels:
      - "coolify.managed=true"

# =====================================================
# VOLUMES
# =====================================================
volumes:
  # PostgreSQL volume removed - using external Supabase

  redis-data:
    driver: local
    labels:
      - "coolify.managed=true"

  app-uploads:
    driver: local
    labels:
      - "coolify.managed=true"

  nginx-cache:
    driver: local
    labels:
      - "coolify.managed=true"

  evolution-instances:
    driver: local
    labels:
      - "coolify.managed=true"

  evolution-store:
    driver: local
    labels:
      - "coolify.managed=true"
